### ISSUE TITLE
Can it run on itself?

### ISSUE THREAD

**Issue by daedalus** [udem-dlteam/pnut#59]

**Comment by laurenthuberdeau** [comment]
Yes!

Pnut can compile itself, which is why it can be distributed as a shell script while being written in C. If you want to test it, you can try `make pnut-bootstrapped.sh` which will bootstrap the compiler using a precompiled `pnut.sh` and compare the result.

This takes a few minutes, and you can follow the progress of the compiler with `tail -f build/pnut-bootstrapped.sh`.

**Comment by daedalus** [comment]
I'm glad. Really nice project.
I'm closing this to not steal more of your time.
